
# ---------- BUILD STAGE ----------
FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

# ---------- RUNTIME STAGE ----------
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 4000

CMD ["node", "index.js"]